version: '3.8'
services:
  photo-family:
    image: postgres:15
    container_name: photo-family-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: photo-family
    ports:
      - '5432:5432'
    volumes:
      - photo-family-db-data:/var/lib/postgresql/data

volumes:
  photo-family-db-data:
